name: guidedlayout2_1604
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+8
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  flutter_native_splash: ^2.2.20
  http: ^0.13.6
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Regular.ttf
        - asset: font/Poppins-Medium.ttf
        - asset: font/Poppins-SemiBold.ttf
        - asset: font/Poppins-Bold.ttf
        - asset: font/Poppins-Italic.ttf
        - asset: font/Poppins-MediumItalic.ttf
        - asset: font/Poppins-SemiBoldItalic.ttf
        - asset: font/Poppins-BoldItalic.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  image: images/Logo.jpg 


  android_12:
    color: "#ffffff"
    image: images/Logo.jpg 
